FROM golang:1.24.4-alpine AS builder
WORKDIR /app

COPY services/order-ms/go.mod services/order-ms/go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

COPY services/order-ms ./services/order-ms
COPY pkg ./pkg

WORKDIR /app/services/order-ms
RUN go build -o /app/order-ms ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/order-ms .
EXPOSE 8084 50054
CMD ["./order-ms"]
