# ---------- Build Stage ----------
FROM golang:1.24.4-alpine AS builder

WORKDIR /app

# Copy go.mod + go.sum first
COPY services/user-ms/go.mod services/user-ms/go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

# Copy source code
COPY services/user-ms ./services/user-ms
COPY pkg ./pkg

# Move into service folder (where go.mod is)
WORKDIR /app/services/user-ms

# Build the binary
RUN go build -o /app/user-ms ./cmd

# ---------- Final Stage ----------
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/user-ms .
EXPOSE 8080 50051
CMD ["./user-ms"]
