basePath: /
definitions:
  domain.Product:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  http.ProductCreateRequest:
    properties:
      description:
        example: High-end gaming laptop
        type: string
      name:
        example: Laptop
        type: string
      price:
        example: 1299.99
        type: number
      stock:
        example: 10
        type: integer
    type: object
  http.ProductUpdateRequest:
    properties:
      description:
        example: Updated description
        type: string
      name:
        example: Laptop
        type: string
      price:
        example: 1199.99
        type: number
      stock:
        example: 15
        type: integer
    type: object
host: localhost:8081
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is the Product service for the e-commerce system.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Product Microservice API
  version: "1.0"
paths:
  /products:
    get:
      description: Get all products (requires JWT)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Add a new product (requires JWT)
      parameters:
      - description: Product info
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/http.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create product
      tags:
      - Products
  /products/{id}:
    delete:
      description: Delete product by ID (requires JWT)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete product
      tags:
      - Products
    get:
      description: Fetch a product by ID (requires JWT)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Product'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update product by ID (requires JWT)
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/http.ProductUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update product
      tags:
      - Products
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
