FROM golang:1.24.4-alpine AS builder
WORKDIR /app

COPY services/cart-ms/go.mod services/cart-ms/go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

COPY services/cart-ms ./services/cart-ms
COPY pkg ./pkg

WORKDIR /app/services/cart-ms
RUN go build -o /app/cart-ms ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/cart-ms .
EXPOSE 8083 50053
CMD ["./cart-ms"]
