FROM golang:1.24.4-alpine AS builder
WORKDIR /app

COPY services/payment-ms/go.mod services/payment-ms/go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

COPY services/payment-ms ./services/payment-ms
COPY pkg ./pkg

WORKDIR /app/services/payment-ms
RUN go build -o /app/payment-ms ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/payment-ms .
EXPOSE 8085 50055
CMD ["./payment-ms"]
