basePath: /
definitions:
  domain.Payment:
    properties:
      amount:
        type: number
      id:
        type: string
      order_id:
        type: string
      status:
        description: PENDING, COMPLETED, FAILED
        type: string
      user_id:
        type: string
    type: object
host: localhost:8085
info:
  contact: {}
  description: Handles payments for orders in the e-commerce system.
  title: Payment Microservice API
  version: "1.0"
paths:
  /payments/{order_id}:
    post:
      description: Create a payment for a given order (requires Bearer token).
      parameters:
      - description: The ID of the order to pay for
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Payment'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create Payment
      tags:
      - Payments
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
