FROM golang:1.24.4-alpine AS builder
WORKDIR /app

COPY services/product-ms/go.mod services/product-ms/go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

COPY services/product-ms ./services/product-ms
COPY pkg ./pkg

WORKDIR /app/services/product-ms
RUN go build -o /app/product-ms ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/product-ms .
EXPOSE 8081 50052
CMD ["./product-ms"]
